"""add project memberships

Revision ID: 79b25c98d726
Revises: fc559495425e
Create Date: 2026-10-05 15:09:49.911535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b25c98d726'
down_revision: Union[str, Sequence[str], None] = 'fc559495425e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN('owner','member')", name='ck_project_membership_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_membership_project_user')
    )
    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memberships_user_id'))

    op.drop_table('project_memberships')
    # ### end Alembic commands ###
